export class LogicLiveEvent {
    static COUNT = 37

    static encode(stream) { 
        stream.writeVInt(4489)
        stream.writeStringReference('BP: Jurassic Brawl Pass')
        stream.writeVInt(5)
        stream.writeVInt(1785751500)
        stream.writeVInt(1788170400)
        stream.writeVInt(1785751500)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('BP: Jurassic Brawl Pass')
        stream.writeString('{"Color":"#cc00ff","BattlepassEventMode":"60","BattlepassShopItemId":"70091","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LogicLiveEvent
        stream.writeVInt(6523)
        stream.writeStringReference('Global Boost: Tribemate Bonus +2')
        stream.writeVInt(3)
        stream.writeVInt(1786752000)
        stream.writeVInt(1786923000)
        stream.writeVInt(1786752000)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Global Boost: Tribemate Bonus +2')
        stream.writeString('{"GlobalEventMode":"10","Color":"#FFBA00","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LogicLiveEvent
        stream.writeVInt(6540)
        stream.writeStringReference('Offer: Event Bomb (Cluster Egg + Clone)')
        stream.writeVInt(0)
        stream.writeVInt(1786667400)
        stream.writeVInt(1786838340)
        stream.writeVInt(1786667400)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Offer: Event Bomb (Cluster Egg + Clone)')
        stream.writeString('{"OverrideName":"TID_SPECIAL_OFFER_EVENT_BOMB","ShopSpenderDaysInActive":30,"ShopSpenderPercentageIncrease":100,"ShopSpenderCapWeekly":false,"ShopSpenderCapMonthly":true,"ShopSpenderCapAllTime":false,"TierDefaultShopItem":"74715","Tier1ShopItem":"74703","Tier2ShopItem":"74703","Tier3ShopItem":"74703","Tier4ShopItem":"74705","Tier5ShopItem":"74705","Tier6ShopItem":"74707","Tier7ShopItem":"74707","Tier8ShopItem":"74710","Tier9ShopItem":"74710","Tier10ShopItem":"74710","Tier15ShopItem":"74715","Tier20ShopItem":"74720","Tier50ShopItem":"74750","Tier60ShopItem":"74760","TierAlternativesEnabled":false,"Color":"#448932","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LogicLiveEvent
        stream.writeVInt(6546)
        stream.writeStringReference('Emojis: Winter Pack')
        stream.writeVInt(7)
        stream.writeVInt(1786665600)
        stream.writeVInt(1786923000)
        stream.writeVInt(1786665600)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Emojis: Winter Pack')
        stream.writeString('{"Color":"#cc00ff","Emoji1":"39","Emoji2":"97","Emoji3":"96","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LogicLiveEvent
        stream.writeVInt(6548)
        stream.writeStringReference('Tower Color: Souvenir from inferno')
        stream.writeVInt(8)
        stream.writeVInt(1786683600)
        stream.writeVInt(1787011140)
        stream.writeVInt(1786683600)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Tower Color: Souvenir from inferno')
        stream.writeString('{"Base1":"1056","Color":"#6600FF","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LogicLiveEvent
        stream.writeVInt(6551)
        stream.writeStringReference('Event: Mind Tick Special Challenge')
        stream.writeVInt(1)
        stream.writeVInt(1786701600)
        stream.writeVInt(1786870800)
        stream.writeVInt(1786698000)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Event: Mind Tick Special Challenge')
        stream.writeString('{"SurvivalMode":"96","Color":"#EC4C2C","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LogicLiveEvent
        stream.writeVInt(6553)
        stream.writeStringReference('Offer: Candy 3 (Rainbow Egg)')
        stream.writeVInt(0)
        stream.writeVInt(1786840200)
        stream.writeVInt(1787011140)
        stream.writeVInt(1786840200)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Offer: Candy 3 (Rainbow Egg)')
        stream.writeString('{"OverrideName":"TID_SPECIAL_OFFER_CANDY_3","ShopSpenderDaysInActive":30,"ShopSpenderPercentageIncrease":100,"ShopSpenderCapWeekly":true,"ShopSpenderCapMonthly":false,"ShopSpenderCapAllTime":false,"TierDefaultShopItem":"78107","Tier1ShopItem":"78102","Tier2ShopItem":"78102","Tier3ShopItem":"78103","Tier4ShopItem":"78105","Tier5ShopItem":"78105","Tier6ShopItem":"78107","Tier7ShopItem":"78107","Tier8ShopItem":"78110","Tier9ShopItem":"78110","Tier10ShopItem":"78110","Tier15ShopItem":"78115","Tier20ShopItem":"78120","Tier50ShopItem":"78120","Tier60ShopItem":"78120","TierAlternativesEnabled":false,"Color":"#448932","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LogicLiveEvent
        stream.writeVInt(6554)
        stream.writeStringReference('Offer: Week (Unreal Egg)')
        stream.writeVInt(0)
        stream.writeVInt(1787185800)
        stream.writeVInt(1787356740)
        stream.writeVInt(1787185800)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Offer: Week (Unreal Egg)')
        stream.writeString('{"OverrideName":"TID_SPECIAL_OFFER_WEEK","ShopSpenderDaysInActive":30,"ShopSpenderPercentageIncrease":100,"ShopSpenderCapWeekly":false,"ShopSpenderCapMonthly":true,"ShopSpenderCapAllTime":false,"TierDefaultShopItem":"78510","Tier1ShopItem":"78505","Tier2ShopItem":"78505","Tier3ShopItem":"78505","Tier4ShopItem":"78505","Tier5ShopItem":"78505","Tier6ShopItem":"78507","Tier7ShopItem":"78507","Tier8ShopItem":"78510","Tier9ShopItem":"78510","Tier10ShopItem":"78510","Tier15ShopItem":"78515","Tier20ShopItem":"78520","Tier50ShopItem":"78520","Tier60ShopItem":"78520","TierAlternativesEnabled":false,"Color":"#448932","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LogicLiveEvent
        stream.writeVInt(6555)
        stream.writeStringReference('Offer: Rune (Rune Egg)')
        stream.writeVInt(0)
        stream.writeVInt(1787531400)
        stream.writeVInt(1787702340)
        stream.writeVInt(1787531400)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Offer: Rune (Rune Egg)')
        stream.writeString('{"OverrideName":"TID_SPECIAL_OFFER_RUNE","ShopSpenderDaysInActive":30,"ShopSpenderPercentageIncrease":100,"ShopSpenderCapWeekly":false,"ShopSpenderCapMonthly":true,"ShopSpenderCapAllTime":false,"TierDefaultShopItem":"80002","Tier1ShopItem":"80002","Tier2ShopItem":"80002","Tier3ShopItem":"80003","Tier4ShopItem":"80005","Tier5ShopItem":"80005","Tier6ShopItem":"80007","Tier7ShopItem":"80007","Tier8ShopItem":"80010","Tier9ShopItem":"80010","Tier10ShopItem":"80010","Tier15ShopItem":"80015","Tier20ShopItem":"80020","Tier50ShopItem":"80020","Tier60ShopItem":"80020","TierAlternativesEnabled":false,"Color":"#448932","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LogicLiveEvent
        stream.writeVInt(6557)
        stream.writeStringReference('Offer: Corelightning (Unstable Egg)')
        stream.writeVInt(0)
        stream.writeVInt(1787013000)
        stream.writeVInt(1787183940)
        stream.writeVInt(1787013000)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Offer: Corelightning (Unstable Egg)')
        stream.writeString('{"OverrideName":"TID_SPECIAL_OFFER_CORELIGHTNING","ShopSpenderDaysInActive":30,"ShopSpenderPercentageIncrease":100,"ShopSpenderCapWeekly":false,"ShopSpenderCapMonthly":true,"ShopSpenderCapAllTime":false,"TierDefaultShopItem":"74815","Tier1ShopItem":"74807","Tier2ShopItem":"74807","Tier3ShopItem":"74807","Tier4ShopItem":"74807","Tier5ShopItem":"74807","Tier6ShopItem":"74807","Tier7ShopItem":"74807","Tier8ShopItem":"74810","Tier9ShopItem":"74810","Tier10ShopItem":"74810","Tier15ShopItem":"74815","Tier20ShopItem":"74815","Tier50ShopItem":"74815","Tier60ShopItem":"74815","TierAlternativesEnabled":false,"Color":"#448932","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LogicLiveEvent
        stream.writeVInt(6558)
        stream.writeStringReference('Offer: Chocolate 2 (Chocolate A Egg)')
        stream.writeVInt(0)
        stream.writeVInt(1787358600)
        stream.writeVInt(1787529540)
        stream.writeVInt(1787358600)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Offer: Chocolate 2 (Chocolate A Egg)')
        stream.writeString('{"OverrideName":"TID_SPECIAL_OFFER_CHOCOLATE_2","ShopSpenderDaysInActive":30,"ShopSpenderPercentageIncrease":100,"ShopSpenderCapWeekly":false,"ShopSpenderCapMonthly":true,"ShopSpenderCapAllTime":false,"TierDefaultShopItem":"72010","Tier1ShopItem":"72002","Tier2ShopItem":"72002","Tier3ShopItem":"72003","Tier4ShopItem":"72005","Tier5ShopItem":"72005","Tier6ShopItem":"72007","Tier7ShopItem":"72007","Tier8ShopItem":"72010","Tier9ShopItem":"72010","Tier10ShopItem":"72010","Tier15ShopItem":"72015","Tier20ShopItem":"72020","Tier50ShopItem":"72050","Tier60ShopItem":"72060","TierAlternativesEnabled":false,"Color":"#448932","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LogicLiveEvent
        stream.writeVInt(6559)
        stream.writeStringReference('Offer: Power 4 (Super Power Egg)')
        stream.writeVInt(0)
        stream.writeVInt(1787704200)
        stream.writeVInt(1787875140)
        stream.writeVInt(1787704200)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Offer: Power 4 (Super Power Egg)')
        stream.writeString('{"OverrideName":"TID_SPECIAL_OFFER_POWER_4","ShopSpenderDaysInActive":30,"ShopSpenderPercentageIncrease":100,"ShopSpenderCapWeekly":false,"ShopSpenderCapMonthly":true,"ShopSpenderCapAllTime":false,"TierDefaultShopItem":"78320","Tier1ShopItem":"78301","Tier2ShopItem":"78302","Tier3ShopItem":"78303","Tier4ShopItem":"78305","Tier5ShopItem":"78305","Tier6ShopItem":"78307","Tier7ShopItem":"78307","Tier8ShopItem":"78310","Tier9ShopItem":"78310","Tier10ShopItem":"78310","Tier15ShopItem":"78315","Tier20ShopItem":"78320","Tier50ShopItem":"78350","Tier60ShopItem":"78360","TierAlternativesEnabled":false,"Color":"#448932","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LogicLiveEvent
        stream.writeVInt(6561)
        stream.writeStringReference('Emojis: Brawl Ball Pack')
        stream.writeVInt(7)
        stream.writeVInt(1786924800)
        stream.writeVInt(1787095800)
        stream.writeVInt(1786924800)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Emojis: Brawl Ball Pack')
        stream.writeString('{"Emoji1":"147","Color":"#CC00FF","Emoji2":"145","Emoji3":"146","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LogicLiveEvent
        stream.writeVInt(6562)
        stream.writeStringReference('Event: Dagger Twins Special Challenge')
        stream.writeVInt(1)
        stream.writeVInt(1787133600)
        stream.writeVInt(1787216400)
        stream.writeVInt(1787130000)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Event: Dagger Twins Special Challenge')
        stream.writeString('{"SurvivalMode":"99","Color":"#EC4C2C","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LogicLiveEvent
        stream.writeVInt(6563)
        stream.writeStringReference('Emojis: King Clony Pack')
        stream.writeVInt(7)
        stream.writeVInt(1787270400)
        stream.writeVInt(1787527800)
        stream.writeVInt(1787270400)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Emojis: King Clony Pack')
        stream.writeString('{"Emoji1":"6","Color":"#CC00FF","Emoji2":"0","Emoji3":"38","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LogicLiveEvent
        stream.writeVInt(6564)
        stream.writeStringReference('Lucky Monday: Boty Eggs')
        stream.writeVInt(3)
        stream.writeVInt(1786924800)
        stream.writeVInt(1787009400)
        stream.writeVInt(1786924800)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Lucky Monday: Boty Eggs')
        stream.writeString('{"GlobalEventMode":"20","Color":"#FFBA00","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LogicLiveEvent
        stream.writeVInt(6565)
        stream.writeStringReference('Lucky Monday: Boty Eggs')
        stream.writeVInt(3)
        stream.writeVInt(1787529600)
        stream.writeVInt(1787614200)
        stream.writeVInt(1787529600)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Lucky Monday: Boty Eggs')
        stream.writeString('{"GlobalEventMode":"20","Color":"#FFBA00","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LogicLiveEvent
        stream.writeVInt(6566)
        stream.writeStringReference('Golden Tuesday')
        stream.writeVInt(3)
        stream.writeVInt(1787011200)
        stream.writeVInt(1787095800)
        stream.writeVInt(1787011200)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Golden Tuesday')
        stream.writeString('{"GlobalEventMode":"44","Color":"#FFBA00","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LogicLiveEvent
        stream.writeVInt(6567)
        stream.writeStringReference('Golden Tuesday')
        stream.writeVInt(3)
        stream.writeVInt(1787616000)
        stream.writeVInt(1787700600)
        stream.writeVInt(1787616000)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Golden Tuesday')
        stream.writeString('{"GlobalEventMode":"44","Color":"#FFBA00","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LogicLiveEvent
        stream.writeVInt(6568)
        stream.writeStringReference('Global Boost: Donation Gold x2')
        stream.writeVInt(3)
        stream.writeVInt(1787097600)
        stream.writeVInt(1787268600)
        stream.writeVInt(1787097600)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Global Boost: Donation Gold x2')
        stream.writeString('{"GlobalEventMode":"12","Color":"#FFBA00","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LogicLiveEvent
        stream.writeVInt(6569)
        stream.writeStringReference('Colossal Friday')
        stream.writeVInt(3)
        stream.writeVInt(1787270400)
        stream.writeVInt(1787355000)
        stream.writeVInt(1787270400)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Colossal Friday')
        stream.writeString('{"GlobalEventMode":"40","Color":"#FFBA00","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LogicLiveEvent
        stream.writeVInt(6571)
        stream.writeStringReference('Global Boost: Tribemate Bonus +2')
        stream.writeVInt(3)
        stream.writeVInt(1787356800)
        stream.writeVInt(1787527800)
        stream.writeVInt(1787356800)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Global Boost: Tribemate Bonus +2')
        stream.writeString('{"GlobalEventMode":"10","Color":"#FFBA00","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LogicLiveEvent
        stream.writeVInt(6572)
        stream.writeStringReference('Global Boost: Victory Gold x2')
        stream.writeVInt(3)
        stream.writeVInt(1787702400)
        stream.writeVInt(1787873400)
        stream.writeVInt(1787702400)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Global Boost: Victory Gold x2')
        stream.writeString('{"GlobalEventMode":"0","Color":"#FFBA00","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LogicLiveEvent
        stream.writeVInt(6574)
        stream.writeStringReference('Event: 2v2 Half Mana Bubble Rush')
        stream.writeVInt(1)
        stream.writeVInt(1786874400)
        stream.writeVInt(1786957200)
        stream.writeVInt(1786870800)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Event: 2v2 Half Mana Bubble Rush')
        stream.writeString('{"SurvivalMode":"154","Color":"#EC4C2C","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LogicLiveEvent
        stream.writeVInt(6575)
        stream.writeStringReference('Event: Blizzard Mayhem')
        stream.writeVInt(1)
        stream.writeVInt(1787047200)
        stream.writeVInt(1787130000)
        stream.writeVInt(1787043600)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Event: Blizzard Mayhem')
        stream.writeString('{"SurvivalMode":"10","Color":"#EC4C2C","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LogicLiveEvent
        stream.writeVInt(6576)
        stream.writeStringReference('Event: Triple Mana Rush')
        stream.writeVInt(1)
        stream.writeVInt(1787220000)
        stream.writeVInt(1787302800)
        stream.writeVInt(1787216400)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Event: Triple Mana Rush')
        stream.writeString('{"SurvivalMode":"7","Color":"#EC4C2C","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LogicLiveEvent
        stream.writeVInt(6577)
        stream.writeStringReference('Event: 2V2 Brawl Showdown')
        stream.writeVInt(1)
        stream.writeVInt(1787479200)
        stream.writeVInt(1787562000)
        stream.writeVInt(1787475600)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Event: 2V2 Brawl Showdown')
        stream.writeString('{"SurvivalMode":"127","Color":"#EC4C2C","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LogicLiveEvent
        stream.writeVInt(6578)
        stream.writeStringReference('Event: Darkness Mayhem')
        stream.writeVInt(1)
        stream.writeVInt(1787652000)
        stream.writeVInt(1787734800)
        stream.writeVInt(1787648400)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Event: Darkness Mayhem')
        stream.writeString('{"SurvivalMode":"11","Color":"#EC4C2C","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LogicLiveEvent
        stream.writeVInt(6579)
        stream.writeStringReference('Event: Double Mana Bubble Rush')
        stream.writeVInt(1)
        stream.writeVInt(1787824800)
        stream.writeVInt(1787907600)
        stream.writeVInt(1787821200)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Event: Double Mana Bubble Rush')
        stream.writeString('{"SurvivalMode":"22","Color":"#EC4C2C","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LogicLiveEvent
        stream.writeVInt(6581)
        stream.writeStringReference('Event: Sudden Death (B)')
        stream.writeVInt(1)
        stream.writeVInt(1786960800)
        stream.writeVInt(1787043600)
        stream.writeVInt(1786957200)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Event: Sudden Death (B)')
        stream.writeString('{"SurvivalMode":"19","Color":"#EC4C2C","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LogicLiveEvent
        stream.writeVInt(6582)
        stream.writeStringReference('Event: Sudden Death (A)')
        stream.writeVInt(1)
        stream.writeVInt(1787565600)
        stream.writeVInt(1787648400)
        stream.writeVInt(1787562000)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Event: Sudden Death (A)')
        stream.writeString('{"SurvivalMode":"18","Color":"#EC4C2C","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LogicLiveEvent
        stream.writeVInt(6583)
        stream.writeStringReference('Event: Healing Bottle Special Challenge')
        stream.writeVInt(1)
        stream.writeVInt(1787133600)
        stream.writeVInt(1787216400)
        stream.writeVInt(1787130000)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Event: Healing Bottle Special Challenge')
        stream.writeString('{"SurvivalMode":"118","Color":"#EC4C2C","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LogicLiveEvent
        stream.writeVInt(6584)
        stream.writeStringReference('Event: Winstreak Challenge')
        stream.writeVInt(1)
        stream.writeVInt(1787306400)
        stream.writeVInt(1787475600)
        stream.writeVInt(1787302800)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Event: Winstreak Challenge')
        stream.writeString('{"SurvivalMode":"129","Color":"#EC4C2C","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LogicLiveEvent
        stream.writeVInt(6585)
        stream.writeStringReference('Event: Sticky Bomb Special Challenge')
        stream.writeVInt(1)
        stream.writeVInt(1787738400)
        stream.writeVInt(1787821200)
        stream.writeVInt(1787734800)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Event: Sticky Bomb Special Challenge')
        stream.writeString('{"SurvivalMode":"112","Color":"#EC4C2C","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LogicLiveEvent
        stream.writeVInt(6587)
        stream.writeStringReference('Tower: Rusty Egg')
        stream.writeVInt(8)
        stream.writeVInt(1787288400)
        stream.writeVInt(1787615940)
        stream.writeVInt(1787288400)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Tower: Rusty Egg')
        stream.writeString('{"Base1":"80","Color":"#6600FF","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LogicLiveEvent
        stream.writeVInt(6589)
        stream.writeStringReference('Emojis: Tongue Out Pack')
        stream.writeVInt(7)
        stream.writeVInt(1787529600)
        stream.writeVInt(1787700600)
        stream.writeVInt(1787529600)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Emojis: Tongue Out Pack')
        stream.writeString('{"Emoji1":"52","Color":"#CC00FF","Emoji2":"89","Emoji3":"90","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LogicLiveEvent
        stream.writeVInt(6590)
        stream.writeStringReference('Emojis: Fire Pack')
        stream.writeVInt(7)
        stream.writeVInt(1787702400)
        stream.writeVInt(1787873400)
        stream.writeVInt(1787702400)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Emojis: Fire Pack')
        stream.writeString('{"Emoji1":"63","Color":"#CC00FF","Emoji2":"35","Emoji3":"64","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)
    }
}