export class LogicLiveEvent {
    static COUNT = 41

    static encode(stream) { 
        // LiveEvent
        stream.writeVInt(4486)
        stream.writeStringReference('BP: Hammer Brawl Pass')
        stream.writeVInt(5)
        stream.writeVInt(1778493900)
        stream.writeVInt(1780912800)
        stream.writeVInt(1778493900)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('BP: Hammer Brawl Pass')
        stream.writeString('{"Color":"#cc00ff","BattlepassEventMode":"46","BattlepassShopItemId":"70088","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LiveEvent
        stream.writeVInt(4487)
        stream.writeStringReference('BP: Temple Brawl Pass')
        stream.writeVInt(5)
        stream.writeVInt(1780913100)
        stream.writeVInt(1783332000)
        stream.writeVInt(1780913100)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('BP: Temple Brawl Pass')
        stream.writeString('{"Color":"#cc00ff","BattlepassEventMode":"50","BattlepassShopItemId":"70089","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LiveEvent
        stream.writeVInt(6319)
        stream.writeStringReference('Event: 2v2 Bomb Rain Mayhem')
        stream.writeVInt(1)
        stream.writeVInt(1780221600)
        stream.writeVInt(1780304400)
        stream.writeVInt(1780218000)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Event: 2v2 Bomb Rain Mayhem')
        stream.writeString('{"SurvivalMode":"152","Color":"#EC4C2C","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LiveEvent
        stream.writeVInt(6321)
        stream.writeStringReference('Event: Sudden Death (A)')
        stream.writeVInt(1)
        stream.writeVInt(1780308000)
        stream.writeVInt(1780390800)
        stream.writeVInt(1780304400)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Event: Sudden Death (A)')
        stream.writeString('{"SurvivalMode":"18","Color":"#EC4C2C","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LiveEvent
        stream.writeVInt(6332)
        stream.writeStringReference('Offer: Chocolate 2 (Chocolate A Egg)')
        stream.writeVInt(0)
        stream.writeVInt(1780101000)
        stream.writeVInt(1780271940)
        stream.writeVInt(1780101000)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Offer: Chocolate 2 (Chocolate A Egg)')
        stream.writeString('{"OverrideName":"TID_SPECIAL_OFFER_CHOCOLATE_2","ShopSpenderDaysInActive":30,"ShopSpenderPercentageIncrease":100,"ShopSpenderCapWeekly":false,"ShopSpenderCapMonthly":true,"ShopSpenderCapAllTime":false,"TierDefaultShopItem":"72010","Tier1ShopItem":"72002","Tier2ShopItem":"72002","Tier3ShopItem":"72003","Tier4ShopItem":"72005","Tier5ShopItem":"72005","Tier6ShopItem":"72007","Tier7ShopItem":"72007","Tier8ShopItem":"72010","Tier9ShopItem":"72010","Tier10ShopItem":"72010","Tier15ShopItem":"72015","Tier20ShopItem":"72020","Tier50ShopItem":"72050","Tier60ShopItem":"72060","TierAlternativesEnabled":false,"Color":"#448932","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LiveEvent
        stream.writeVInt(6333)
        stream.writeStringReference('Offer: Rune (Rune Egg)')
        stream.writeVInt(0)
        stream.writeVInt(1780273800)
        stream.writeVInt(1780444740)
        stream.writeVInt(1780273800)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Offer: Rune (Rune Egg)')
        stream.writeString('{"OverrideName":"TID_SPECIAL_OFFER_RUNE","ShopSpenderDaysInActive":30,"ShopSpenderPercentageIncrease":100,"ShopSpenderCapWeekly":false,"ShopSpenderCapMonthly":true,"ShopSpenderCapAllTime":false,"TierDefaultShopItem":"80002","Tier1ShopItem":"80002","Tier2ShopItem":"80002","Tier3ShopItem":"80003","Tier4ShopItem":"80005","Tier5ShopItem":"80005","Tier6ShopItem":"80007","Tier7ShopItem":"80007","Tier8ShopItem":"80010","Tier9ShopItem":"80010","Tier10ShopItem":"80010","Tier15ShopItem":"80015","Tier20ShopItem":"80020","Tier50ShopItem":"80020","Tier60ShopItem":"80020","TierAlternativesEnabled":false,"Color":"#448932","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LiveEvent
        stream.writeVInt(6339)
        stream.writeStringReference('Emojis: King Clony Pack')
        stream.writeVInt(7)
        stream.writeVInt(1780012800)
        stream.writeVInt(1780270200)
        stream.writeVInt(1780012800)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Emojis: King Clony Pack')
        stream.writeString('{"Emoji1":"6","Color":"#CC00FF","Emoji2":"0","Emoji3":"38","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LiveEvent
        stream.writeVInt(6341)
        stream.writeStringReference('Tower: Banana')
        stream.writeVInt(8)
        stream.writeVInt(1780030800)
        stream.writeVInt(1780358340)
        stream.writeVInt(1780030800)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Tower: Banana')
        stream.writeString('{"Base1":"11","Color":"#6600FF","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LiveEvent
        stream.writeVInt(6344)
        stream.writeStringReference('Lucky Monday: Boty Eggs')
        stream.writeVInt(3)
        stream.writeVInt(1780272000)
        stream.writeVInt(1780356600)
        stream.writeVInt(1780272000)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Lucky Monday: Boty Eggs')
        stream.writeString('{"GlobalEventMode":"20","Color":"#FFBA00","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LiveEvent
        stream.writeVInt(6347)
        stream.writeStringReference('Golden Tuesday')
        stream.writeVInt(3)
        stream.writeVInt(1780358400)
        stream.writeVInt(1780443000)
        stream.writeVInt(1780358400)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Golden Tuesday')
        stream.writeString('{"GlobalEventMode":"44","Color":"#FFBA00","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LiveEvent
        stream.writeVInt(6352)
        stream.writeStringReference('Global Boost: Tribemate Bonus +2')
        stream.writeVInt(3)
        stream.writeVInt(1780099200)
        stream.writeVInt(1780270200)
        stream.writeVInt(1780099200)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Global Boost: Tribemate Bonus +2')
        stream.writeString('{"GlobalEventMode":"10","Color":"#FFBA00","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LiveEvent
        stream.writeVInt(6354)
        stream.writeStringReference('Emojis: Pinata Pack')
        stream.writeVInt(7)
        stream.writeVInt(1780272000)
        stream.writeVInt(1780443000)
        stream.writeVInt(1780272000)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Emojis: Pinata Pack')
        stream.writeString('{"Emoji1":"292","Color":"#CC00FF","Emoji2":"294","Emoji3":"293","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LiveEvent
        stream.writeVInt(6355)
        stream.writeStringReference('Emojis: Angry Pack')
        stream.writeVInt(7)
        stream.writeVInt(1780444800)
        stream.writeVInt(1780615800)
        stream.writeVInt(1780444800)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Emojis: Angry Pack')
        stream.writeString('{"Emoji1":"32","Color":"#CC00FF","Emoji2":"67","Emoji3":"81","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LiveEvent
        stream.writeVInt(6356)
        stream.writeStringReference('Emojis: Brawl Ball Pack without King Ball')
        stream.writeVInt(7)
        stream.writeVInt(1780617600)
        stream.writeVInt(1780875000)
        stream.writeVInt(1780617600)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Emojis: Brawl Ball Pack without King Ball')
        stream.writeString('{"Emoji1":"147","Color":"#CC00FF","Emoji2":"145","Emoji3":"146","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LiveEvent
        stream.writeVInt(6357)
        stream.writeStringReference('Emojis: Esport Pack')
        stream.writeVInt(7)
        stream.writeVInt(1780876800)
        stream.writeVInt(1781047800)
        stream.writeVInt(1780876800)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Emojis: Esport Pack')
        stream.writeString('{"Emoji1":"50","Color":"#CC00FF","Emoji2":"48","Emoji3":"52","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LiveEvent
        stream.writeVInt(6358)
        stream.writeStringReference('Emojis: BlingBling Pack')
        stream.writeVInt(7)
        stream.writeVInt(1781049600)
        stream.writeVInt(1781220600)
        stream.writeVInt(1781049600)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Emojis: BlingBling Pack')
        stream.writeString('{"Emoji1":"66","Color":"#CC00FF","Emoji2":"65","Emoji3":"27","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LiveEvent
        stream.writeVInt(6359)
        stream.writeStringReference('Emojis: LumberJackie Coffee Pack')
        stream.writeVInt(7)
        stream.writeVInt(1781222400)
        stream.writeVInt(1781479800)
        stream.writeVInt(1781222400)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Emojis: LumberJackie Coffee Pack')
        stream.writeString('{"Emoji1":"169","Color":"#CC00FF","Emoji2":"170","Emoji3":"171","Emoji4":"172","Emoji5":"9","Emoji6":"42","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LiveEvent
        stream.writeVInt(6360)
        stream.writeStringReference('Tower Color: Our Lord and Savior')
        stream.writeVInt(8)
        stream.writeVInt(1780635600)
        stream.writeVInt(1780963140)
        stream.writeVInt(1780635600)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Tower Color: Our Lord and Savior')
        stream.writeString('{"Base1":"1028","Color":"#6600FF","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LiveEvent
        stream.writeVInt(6361)
        stream.writeStringReference('Tower: Spooky')
        stream.writeVInt(8)
        stream.writeVInt(1781240400)
        stream.writeVInt(1781567940)
        stream.writeVInt(1781240400)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Tower: Spooky')
        stream.writeString('{"Base1":"3","Color":"#6600FF","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LiveEvent
        stream.writeVInt(6362)
        stream.writeStringReference('Global Boost: Victory Gold x2')
        stream.writeVInt(3)
        stream.writeVInt(1780444800)
        stream.writeVInt(1780615800)
        stream.writeVInt(1780444800)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Global Boost: Victory Gold x2')
        stream.writeString('{"GlobalEventMode":"0","Color":"#FFBA00","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LiveEvent
        stream.writeVInt(6364)
        stream.writeStringReference('Colossal Friday')
        stream.writeVInt(3)
        stream.writeVInt(1780617600)
        stream.writeVInt(1780702200)
        stream.writeVInt(1780617600)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Colossal Friday')
        stream.writeString('{"GlobalEventMode":"40","Color":"#FFBA00","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LiveEvent
        stream.writeVInt(6365)
        stream.writeStringReference('Colossal Friday')
        stream.writeVInt(3)
        stream.writeVInt(1781222400)
        stream.writeVInt(1781307000)
        stream.writeVInt(1781222400)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Colossal Friday')
        stream.writeString('{"GlobalEventMode":"40","Color":"#FFBA00","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LiveEvent
        stream.writeVInt(6368)
        stream.writeStringReference('Global Boost: Gear Multiplier x2')
        stream.writeVInt(3)
        stream.writeVInt(1780704000)
        stream.writeVInt(1780875000)
        stream.writeVInt(1780704000)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Global Boost: Gear Multiplier x2')
        stream.writeString('{"GlobalEventMode":"37","Color":"#FFBA00","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LiveEvent
        stream.writeVInt(6369)
        stream.writeStringReference('Lucky Monday: Chocolate Love Eggs')
        stream.writeVInt(3)
        stream.writeVInt(1780876800)
        stream.writeVInt(1780961400)
        stream.writeVInt(1780876800)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Lucky Monday: Chocolate Love Eggs')
        stream.writeString('{"GlobalEventMode":"24","Color":"#FFBA00","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LiveEvent
        stream.writeVInt(6373)
        stream.writeStringReference('Golden Tuesday')
        stream.writeVInt(3)
        stream.writeVInt(1780963200)
        stream.writeVInt(1781047800)
        stream.writeVInt(1780963200)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Golden Tuesday')
        stream.writeString('{"GlobalEventMode":"44","Color":"#FFBA00","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LiveEvent
        stream.writeVInt(6377)
        stream.writeStringReference('Global Boost: Donation Gold x2')
        stream.writeVInt(3)
        stream.writeVInt(1781049600)
        stream.writeVInt(1781220600)
        stream.writeVInt(1781049600)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Global Boost: Donation Gold x2')
        stream.writeString('{"GlobalEventMode":"12","Color":"#FFBA00","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LiveEvent
        stream.writeVInt(6382)
        stream.writeStringReference('Event: Quake Mayhem')
        stream.writeVInt(1)
        stream.writeVInt(1780394400)
        stream.writeVInt(1780477200)
        stream.writeVInt(1780390800)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Event: Quake Mayhem')
        stream.writeString('{"SurvivalMode":"9","Color":"#EC4C2C","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LiveEvent
        stream.writeVInt(6383)
        stream.writeStringReference('Event: Wildfire Special Challenge')
        stream.writeVInt(1)
        stream.writeVInt(1780480800)
        stream.writeVInt(1780563600)
        stream.writeVInt(1780477200)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Event: Wildfire Special Challenge')
        stream.writeString('{"SurvivalMode":"119","Color":"#EC4C2C","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LiveEvent
        stream.writeVInt(6384)
        stream.writeStringReference('Event: Triple Mana Rush')
        stream.writeVInt(1)
        stream.writeVInt(1780567200)
        stream.writeVInt(1780650000)
        stream.writeVInt(1780563600)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Event: Triple Mana Rush')
        stream.writeString('{"SurvivalMode":"7","Color":"#EC4C2C","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LiveEvent
        stream.writeVInt(6385)
        stream.writeStringReference('Offer: Power 4 (Super Power Egg)')
        stream.writeVInt(0)
        stream.writeVInt(1780446600)
        stream.writeVInt(1780617540)
        stream.writeVInt(1780446600)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Offer: Power 4 (Super Power Egg)')
        stream.writeString('{"OverrideName":"TID_SPECIAL_OFFER_POWER_4","ShopSpenderDaysInActive":30,"ShopSpenderPercentageIncrease":100,"ShopSpenderCapWeekly":false,"ShopSpenderCapMonthly":true,"ShopSpenderCapAllTime":false,"TierDefaultShopItem":"78320","Tier1ShopItem":"78301","Tier2ShopItem":"78302","Tier3ShopItem":"78303","Tier4ShopItem":"78305","Tier5ShopItem":"78305","Tier6ShopItem":"78307","Tier7ShopItem":"78307","Tier8ShopItem":"78310","Tier9ShopItem":"78310","Tier10ShopItem":"78310","Tier15ShopItem":"78315","Tier20ShopItem":"78320","Tier50ShopItem":"78350","Tier60ShopItem":"78360","TierAlternativesEnabled":false,"Color":"#448932","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LiveEvent
        stream.writeVInt(6386)
        stream.writeStringReference('Event: Bomb Drone Special Challenge')
        stream.writeVInt(1)
        stream.writeVInt(1780653600)
        stream.writeVInt(1780822800)
        stream.writeVInt(1780650000)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Event: Bomb Drone Special Challenge')
        stream.writeString('{"SurvivalMode":"78","Color":"#EC4C2C","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LiveEvent
        stream.writeVInt(6387)
        stream.writeStringReference('Offer: Christmas 3 (Gift Egg)')
        stream.writeVInt(0)
        stream.writeVInt(1780619400)
        stream.writeVInt(1780790340)
        stream.writeVInt(1780619400)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Offer: Christmas 3 (Gift Egg)')
        stream.writeString('{"OverrideName":"TID_SPECIAL_OFFER_CHRISTMAS_3","ShopSpenderDaysInActive":30,"ShopSpenderPercentageIncrease":100,"ShopSpenderCapWeekly":false,"ShopSpenderCapMonthly":true,"ShopSpenderCapAllTime":false,"TierDefaultShopItem":"70310","Tier1ShopItem":"70301","Tier2ShopItem":"70302","Tier3ShopItem":"70303","Tier4ShopItem":"70305","Tier5ShopItem":"70305","Tier6ShopItem":"70307","Tier7ShopItem":"70307","Tier8ShopItem":"70310","Tier9ShopItem":"70310","Tier10ShopItem":"70310","Tier15ShopItem":"70315","Tier20ShopItem":"70320","Tier50ShopItem":"70350","Tier60ShopItem":"70360","TierAlternativesEnabled":false,"Color":"#448932","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LiveEvent
        stream.writeVInt(6388)
        stream.writeStringReference('Offer: Season 2 (Ultra Booster Egg)')
        stream.writeVInt(0)
        stream.writeVInt(1780792200)
        stream.writeVInt(1780963140)
        stream.writeVInt(1780792200)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Offer: Season 2 (Ultra Booster Egg)')
        stream.writeString('{"OverrideName":"TID_SPECIAL_OFFER_SEASON_2","ShopSpenderDaysInActive":30,"ShopSpenderPercentageIncrease":100,"ShopSpenderCapWeekly":false,"ShopSpenderCapMonthly":true,"ShopSpenderCapAllTime":false,"TierDefaultShopItem":"73910","Tier1ShopItem":"73910","Tier2ShopItem":"73910","Tier3ShopItem":"73910","Tier4ShopItem":"73910","Tier5ShopItem":"73910","Tier6ShopItem":"73910","Tier7ShopItem":"73910","Tier8ShopItem":"73910","Tier9ShopItem":"73910","Tier10ShopItem":"73910","Tier15ShopItem":"73915","Tier20ShopItem":"73920","Tier50ShopItem":"73950","Tier60ShopItem":"73960","TierAlternativesEnabled":false,"Color":"#448932","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LiveEvent
        stream.writeVInt(6389)
        stream.writeStringReference('Offer: Season 5 (Sentinel Egg)')
        stream.writeVInt(0)
        stream.writeVInt(1780965000)
        stream.writeVInt(1781135940)
        stream.writeVInt(1780965000)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Offer: Season 5 (Sentinel Egg)')
        stream.writeString('{"OverrideName":"TID_SPECIAL_OFFER_SEASON_5","ShopSpenderDaysInActive":30,"ShopSpenderPercentageIncrease":100,"ShopSpenderCapWeekly":false,"ShopSpenderCapMonthly":true,"ShopSpenderCapAllTime":false,"TierDefaultShopItem":"73020","Tier1ShopItem":"73003","Tier2ShopItem":"73003","Tier3ShopItem":"73003","Tier4ShopItem":"73005","Tier5ShopItem":"73005","Tier6ShopItem":"73007","Tier7ShopItem":"73007","Tier8ShopItem":"73010","Tier9ShopItem":"73010","Tier10ShopItem":"73010","Tier15ShopItem":"73015","Tier20ShopItem":"73020","Tier50ShopItem":"73050","Tier60ShopItem":"73050","TierAlternativesEnabled":false,"Color":"#448932","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LiveEvent
        stream.writeVInt(6390)
        stream.writeStringReference('Offer: Corelightning (Unstable Egg)')
        stream.writeVInt(0)
        stream.writeVInt(1781137800)
        stream.writeVInt(1781308740)
        stream.writeVInt(1781137800)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Offer: Corelightning (Unstable Egg)')
        stream.writeString('{"OverrideName":"TID_SPECIAL_OFFER_CORELIGHTNING","ShopSpenderDaysInActive":30,"ShopSpenderPercentageIncrease":100,"ShopSpenderCapWeekly":false,"ShopSpenderCapMonthly":true,"ShopSpenderCapAllTime":false,"TierDefaultShopItem":"74815","Tier1ShopItem":"74807","Tier2ShopItem":"74807","Tier3ShopItem":"74807","Tier4ShopItem":"74807","Tier5ShopItem":"74807","Tier6ShopItem":"74807","Tier7ShopItem":"74807","Tier8ShopItem":"74810","Tier9ShopItem":"74810","Tier10ShopItem":"74810","Tier15ShopItem":"74815","Tier20ShopItem":"74815","Tier50ShopItem":"74815","Tier60ShopItem":"74815","TierAlternativesEnabled":false,"Color":"#448932","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LiveEvent
        stream.writeVInt(6400)
        stream.writeStringReference('Event: 2v2 Half Mana Bubble Rush')
        stream.writeVInt(1)
        stream.writeVInt(1780826400)
        stream.writeVInt(1780909200)
        stream.writeVInt(1780822800)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Event: 2v2 Half Mana Bubble Rush')
        stream.writeString('{"SurvivalMode":"154","Color":"#EC4C2C","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LiveEvent
        stream.writeVInt(6401)
        stream.writeStringReference('Event: Big Bouncy Bomb Mayhem')
        stream.writeVInt(1)
        stream.writeVInt(1780999200)
        stream.writeVInt(1781082000)
        stream.writeVInt(1780995600)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Event: Big Bouncy Bomb Mayhem')
        stream.writeString('{"SurvivalMode":"1","Color":"#EC4C2C","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LiveEvent
        stream.writeVInt(6402)
        stream.writeStringReference('Event: Triple Mana Rush')
        stream.writeVInt(1)
        stream.writeVInt(1781172000)
        stream.writeVInt(1781254800)
        stream.writeVInt(1781168400)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Event: Triple Mana Rush')
        stream.writeString('{"SurvivalMode":"7","Color":"#EC4C2C","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LiveEvent
        stream.writeVInt(6405)
        stream.writeStringReference('Event: Sudden Death (B)')
        stream.writeVInt(1)
        stream.writeVInt(1780912800)
        stream.writeVInt(1780995600)
        stream.writeVInt(1780909200)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Event: Sudden Death (B)')
        stream.writeString('{"SurvivalMode":"19","Color":"#EC4C2C","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LiveEvent
        stream.writeVInt(6407)
        stream.writeStringReference('Event: Dagger Twins Special Challenge')
        stream.writeVInt(1)
        stream.writeVInt(1781085600)
        stream.writeVInt(1781168400)
        stream.writeVInt(1781082000)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Event: Dagger Twins Special Challenge')
        stream.writeString('{"SurvivalMode":"99","Color":"#EC4C2C","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

        // LiveEvent
        stream.writeVInt(6408)
        stream.writeStringReference('Event: Gold Rush')
        stream.writeVInt(1)
        stream.writeVInt(1781258400)
        stream.writeVInt(1781427600)
        stream.writeVInt(1781254800)
        stream.writeStringReference('')
        stream.writeStringReference('')
        stream.writeStringReference('Event: Gold Rush')
        stream.writeString('{"SurvivalMode":"15","Color":"#EC4C2C","lookupValues":[]}')
        stream.writeVInt(0)
        stream.writeBoolean(false)

    }
}