export class LogicShop {
    static encode(stream) {
        stream.writeBoolean(true)
        stream.writeVInt(1)
        stream.writeVInt(0)
        stream.writeBoolean(false)
        stream.writeVInt(-308874347)
        stream.writeVInt(3)
        stream.writeVInt(1)
        stream.writeVInt(1)
        stream.writeVInt(0)
        stream.writeVInt(6388)
        stream.writeVInt(-1)
        stream.writeVInt(-1)
        stream.writeVInt(0)
        stream.writeVInt(0)
        // LogicTimer
        stream.writeVInt(444660)
        stream.writeVInt(444660)
        stream.writeVInt(1780869599)

        stream.writeBoolean(false)
        stream.writeBoolean(true)
        stream.writeVInt(8)

        // LogicShopItemInfo
        stream.writeVInt(73910)
        stream.writeVInt(0)
        stream.writeVInt(6388)
        stream.writeVInt(1780792200)
        stream.writeVInt(1780963140)
        stream.writeVInt(0)
        stream.writeVInt(1)
        stream.writeBoolean(false)
        stream.writeBoolean(false)
        // LogicShopItemInfoSpecialOfferChronos
        stream.writeVInt(-1)
        stream.writeVInt(0)
        stream.writeVInt(0)
        stream.writeStringReference('TID_SPECIAL_OFFER_SEASON_2')

        // VintArr 1
        stream.writeVInt(61)
        stream.writeVInt(73910)
        stream.writeVInt(73910)
        stream.writeVInt(73910)
        stream.writeVInt(73910)
        stream.writeVInt(73910)
        stream.writeVInt(73910)
        stream.writeVInt(73910)
        stream.writeVInt(73910)
        stream.writeVInt(73910)
        stream.writeVInt(73910)
        stream.writeVInt(73910)
        stream.writeVInt(-1)
        stream.writeVInt(-1)
        stream.writeVInt(-1)
        stream.writeVInt(-1)
        stream.writeVInt(73915)
        stream.writeVInt(-1)
        stream.writeVInt(-1)
        stream.writeVInt(-1)
        stream.writeVInt(-1)
        stream.writeVInt(73920)
        stream.writeVInt(-1)
        stream.writeVInt(-1)
        stream.writeVInt(-1)
        stream.writeVInt(-1)
        stream.writeVInt(-1)
        stream.writeVInt(-1)
        stream.writeVInt(-1)
        stream.writeVInt(-1)
        stream.writeVInt(-1)
        stream.writeVInt(-1)
        stream.writeVInt(-1)
        stream.writeVInt(-1)
        stream.writeVInt(-1)
        stream.writeVInt(-1)
        stream.writeVInt(-1)
        stream.writeVInt(-1)
        stream.writeVInt(-1)
        stream.writeVInt(-1)
        stream.writeVInt(-1)
        stream.writeVInt(-1)
        stream.writeVInt(-1)
        stream.writeVInt(-1)
        stream.writeVInt(-1)
        stream.writeVInt(-1)
        stream.writeVInt(-1)
        stream.writeVInt(-1)
        stream.writeVInt(-1)
        stream.writeVInt(-1)
        stream.writeVInt(-1)
        stream.writeVInt(73950)
        stream.writeVInt(-1)
        stream.writeVInt(-1)
        stream.writeVInt(-1)
        stream.writeVInt(-1)
        stream.writeVInt(-1)
        stream.writeVInt(-1)
        stream.writeVInt(-1)
        stream.writeVInt(-1)
        stream.writeVInt(-1)
        stream.writeVInt(73960)

        stream.writeVInt(30)
        stream.writeVInt(100)
        stream.writeBoolean(false)
        stream.writeBoolean(true)
        stream.writeBoolean(false)
        stream.writeBoolean(false)
        stream.writeVInt(1)
        stream.writeVInt(1)
        // VintArr 2
        stream.writeVInt(0)

        // VintArr 3
        stream.writeVInt(0)

        // VintArr 4
        stream.writeVInt(0)

        // VintArr 5
        stream.writeVInt(0)

        stream.writeVInt(1780847294)
        stream.writeVInt(1780847366)
        stream.writeVInt(0)
        stream.writeBoolean(true)
        stream.writeVInt(3086)
        stream.writeVInt(0)
        stream.writeVInt(-1)
        stream.writeVInt(0)
        stream.writeVInt(-1)
        stream.writeVInt(-1)
        stream.writeVInt(0)
        stream.writeVInt(0)
        stream.writeVInt(3)
        stream.writeVInt(6)
        // LogicShopCycleItem
        stream.writeVInt(0)
        stream.writeVInt(0)
        stream.writeVInt(3086)
        stream.writeVInt(0)
        stream.writeVInt(0)
        stream.writeVInt(0)
        stream.writeBoolean(false)
        stream.writeBoolean(false)
        // EpicDayGift
        stream.writeVInt(2)
        stream.writeVInt(1)
        stream.writeVInt(2)

        stream.writeVInt(1)
        // LogicShopCycleItem
        stream.writeVInt(0)
        stream.writeVInt(1)
        stream.writeVInt(3086)
        stream.writeVInt(100)
        stream.writeVInt(0)
        stream.writeVInt(1)
        stream.writeBoolean(false)
        stream.writeBoolean(false)
        // Spell
        stream.writeVInt(2)
        stream.writeVInt(2)
        stream.writeVInt(1)
        stream.writeBoolean(false)
        stream.writeVInt(800)
        stream.writeVInt(0)

        stream.writeVInt(1)
        // LogicShopCycleItem
        stream.writeVInt(0)
        stream.writeVInt(2)
        stream.writeVInt(3086)
        stream.writeVInt(2000)
        stream.writeVInt(0)
        stream.writeVInt(1)
        stream.writeBoolean(false)
        stream.writeBoolean(false)
        // Spell
        stream.writeVInt(30)
        stream.writeVInt(1)
        stream.writeVInt(2)
        stream.writeBoolean(false)
        stream.writeVInt(800)
        stream.writeVInt(0)

        stream.writeVInt(3)
        stream.writeBoolean(true)
        stream.writeBoolean(false)
        stream.writeBoolean(false)
        stream.writeVInt(0)
        stream.writeVInt(0)
        stream.writeVInt(3)
        // VintArr 6
        stream.writeVInt(0)

        stream.writeVInt(-1)
    }
}