export class LogicSpellDeck {
    static encode(stream) {
        stream.writeBoolean(true)
        stream.writeBoolean(true)
        stream.writeBoolean(true)
        stream.writeBoolean(true)
        stream.writeBoolean(true)
        stream.writeBoolean(true)
        stream.writeBoolean(true)
        stream.writeBoolean(true)

        // LogicSpell
        stream.writeVInt(30)
        stream.writeVInt(0)
        stream.writeVInt(0)
        stream.writeVInt(1)
        stream.writeVInt(2)
        stream.writeVInt(15)
        stream.writeVInt(15)
        stream.writeVInt(0)
        stream.writeVInt(0)
        stream.writeBoolean(true)
        stream.writeBoolean(false)
        stream.writeVInt(-1)
        stream.writeVInt(-1)
        stream.writeVInt(0)

        // LogicSpell
        stream.writeVInt(56)
        stream.writeVInt(1)
        stream.writeVInt(1)
        stream.writeVInt(1)
        stream.writeVInt(0)
        stream.writeVInt(15)
        stream.writeVInt(15)
        stream.writeVInt(0)
        stream.writeVInt(0)
        stream.writeBoolean(false)
        stream.writeBoolean(false)
        stream.writeVInt(-1)
        stream.writeVInt(-1)
        stream.writeVInt(0)

        // LogicSpell
        stream.writeVInt(2)
        stream.writeVInt(0)
        stream.writeVInt(0)
        stream.writeVInt(1)
        stream.writeVInt(2)
        stream.writeVInt(15)
        stream.writeVInt(15)
        stream.writeVInt(0)
        stream.writeVInt(0)
        stream.writeBoolean(true)
        stream.writeBoolean(false)
        stream.writeVInt(-1)
        stream.writeVInt(-1)
        stream.writeVInt(0)

        // LogicSpell
        stream.writeVInt(19)
        stream.writeVInt(1)
        stream.writeVInt(1)
        stream.writeVInt(1)
        stream.writeVInt(1)
        stream.writeVInt(15)
        stream.writeVInt(15)
        stream.writeVInt(0)
        stream.writeVInt(0)
        stream.writeBoolean(false)
        stream.writeBoolean(false)
        stream.writeVInt(-1)
        stream.writeVInt(-1)
        stream.writeVInt(0)

        // LogicSpell
        stream.writeVInt(16)
        stream.writeVInt(0)
        stream.writeVInt(0)
        stream.writeVInt(29680781)
        stream.writeVInt(3)
        stream.writeVInt(13)
        stream.writeVInt(13)
        stream.writeVInt(2)
        stream.writeVInt(0)
        stream.writeBoolean(true)
        stream.writeBoolean(false)
        stream.writeVInt(-1)
        stream.writeVInt(-1)
        stream.writeVInt(0)

        // LogicSpell
        stream.writeVInt(1)
        stream.writeVInt(0)
        stream.writeVInt(0)
        stream.writeVInt(29680781)
        stream.writeVInt(1)
        stream.writeVInt(12)
        stream.writeVInt(12)
        stream.writeVInt(0)
        stream.writeVInt(0)
        stream.writeBoolean(false)
        stream.writeBoolean(false)
        stream.writeVInt(-1)
        stream.writeVInt(-1)
        stream.writeVInt(0)

        // LogicSpell
        stream.writeVInt(10)
        stream.writeVInt(0)
        stream.writeVInt(0)
        stream.writeVInt(29680784)
        stream.writeVInt(1)
        stream.writeVInt(8)
        stream.writeVInt(8)
        stream.writeVInt(0)
        stream.writeVInt(0)
        stream.writeBoolean(false)
        stream.writeBoolean(false)
        stream.writeVInt(-1)
        stream.writeVInt(-1)
        stream.writeVInt(0)

        // LogicSpell
        stream.writeVInt(44)
        stream.writeVInt(0)
        stream.writeVInt(0)
        stream.writeVInt(29680784)
        stream.writeVInt(1)
        stream.writeVInt(7)
        stream.writeVInt(7)
        stream.writeVInt(0)
        stream.writeVInt(0)
        stream.writeBoolean(false)
        stream.writeBoolean(false)
        stream.writeVInt(-1)
        stream.writeVInt(-1)
        stream.writeVInt(0)
    }

    static encode2(stream) {
        stream.writeBoolean(false)
        stream.writeBoolean(false)
        stream.writeBoolean(false)
        stream.writeBoolean(false)
        stream.writeBoolean(false)
        stream.writeBoolean(false)
        stream.writeBoolean(false)
        stream.writeBoolean(false)
    }
}